---
application:
  name: "very-mine"
  project: "Very Paper Master"
  organization: "QoveryCommunity"
  storage:
  - name: "static"
    size: "200"
    type: "fast_ssd"
    mount_point: "/mnt/static"
routers:
- name: "main-very-mine"
  routes:
  - application_name: "very-mine"
    paths:
    - "/*"
